//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess3
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPlayer
    {
        public string UserName { get; set; }
        public string TeamName { get; set; }
        public string PlayerId { get; set; }
        public int Slot_NoDH { get; set; }
        public int Slot_DH { get; set; }
        public int Posn_NoDH { get; set; }
        public int Posn_DH { get; set; }
    }
}
