//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MlbLeague
    {
        public string MlbLeague1 { get; set; }
        public Nullable<int> Year { get; set; }
        public string Stats { get; set; }
        public string Ver { get; set; }
    }
}
