//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MlbPlayer
    {
        public string PlayerName { get; set; }
        public string MlbTeam { get; set; }
        public Nullable<int> Year { get; set; }
        public string FieldingString { get; set; }
        public string PlayerType { get; set; }
        public string Stats { get; set; }
        public string LgStats { get; set; }
        public string Ver { get; set; }
        public string MlbLeague { get; set; }
        public string PlayerId { get; set; }
        public int ab { get; set; }
        public int r { get; set; }
        public int h { get; set; }
        public int rbi { get; set; }
        public int b2 { get; set; }
        public int b3 { get; set; }
        public int hr { get; set; }
    }
}
